### PR TITLE
Feature selector

### PR DESCRIPTION
**Pull request by kevinwho777**
A few functionalities:
1. Feature selector (top n features using Chi squared)
2. Compare feature distribution for good/bad files + density plot for visualization
3. Util funcs

Note: I merged with the feature_data_dir branch locally so it contains the new feature extractor

### CODE REVIEW

**Comment by Sidu28** [comment]
It looks good to me.  I resolved the conflicts so should be good to merge once Manan has made his comments

**Comment by Sidu28** [comment]
Also, please delete any extra branches you have made once you're done merging!

**Review by Sidu28 — APPROVED** [review]
Looks good! I think you can go ahead and merge

**Review by mananshah99 — APPROVED** [review]
LGTM, cool stuff!

**Pull request merged**
