### PR TITLE
Feature distribution

### PR DESCRIPTION
**Pull request by Sidu28**
Added test for random_forest.  Redid data directory structure.

### CODE REVIEW

**Comment by mananshah99** [comment]
Can you resolve the merge conflicts with master?

**Comment by mananshah99** [comment]
Just FYI, when I say "resolve merge conflicts with master" I don't mean "merge the PR into master"; instead, you should pull master into the PR and resolve the merge conflicts. It's better practice to wait until approval before merging the entire PR, and to check the tests before doing so.

**Comment by Sidu28** [comment]
Noted.  Should I revert the merged commit and try and fix the issue?

**Comment by mananshah99** [comment]
It’s not worth reverting the commit since the issue is so minor; seems like sklearn was not part of the requirements.txt or something of that nature. I’d just submit a new PR.

**Pull request merged**
