### PR TITLE
Initial functional web application named "VirusTotal++"

### PR DESCRIPTION
**Pull request by mananshah99**

### CODE REVIEW

**Comment by mananshah99** [comment]
Still need to add instructions for website deployment, but code is functional!

**Comment by mananshah99** [comment]
Reviews would be appreciated about core code functionality. Some additional (minor) bugs have been fixed in #29

**Comment by kevinwho777** [comment]
Code looks good and everything is functional -- definitely a great starting point for webdev

**Review by kevinwho777 — APPROVED** [review]

**Review by Sidu28 — APPROVED** [review]
Looks good @mananshah99

**Pull request merged**
